#########################################################################################################################
# TODO: REPLACE THE CONTENT OF THIS FILE WITH YOUR OWN.
#########################################################################################################################

services:
  web:
    build: .
    image: chall2025-apocalypse
    ports:
      - "2025:80"
